import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Reto } from 'src/app/Models/Reto';
import { ChangeRoute } from 'src/app/Utils/Constants';

@Component({
  selector: 'app-user-reto',
  templateUrl: './user-reto.component.html',
  styleUrls: ['./user-reto.component.css'],
})
export class UserRetoComponent implements OnInit {
  changeRoute = ChangeRoute();
  first: number = 0;
  rows: number = 9; // items por página

  reto: Reto[] = [
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
    {
      idReto: '',
      nombre: 'Reto1 bla bla bla bla bla bla bla bla bla bla bla bla',
      fechaApertura: new Date(),
      fechaCierre: new Date(),
      vidas: 0,
      tiempo_ms: 3600,
      puntosRecompensa: 10,
      creditosObtenidos: 23,
      instrucciones: '',
      imagen: 'imgreto.png',
      idTipoReto: '',
      tipoReto: 'Trivia',
      idComportamiento: '',
      comportamiento: 'aleatoria',
      estado: 0,
    },
  ];

  constructor(private router: Router) {}

  ngOnInit(): void {}

  cargarData() {}

  paginatedItems(): Reto[] {
    const startIndex = this.first;
    const endIndex = startIndex + this.rows;
    return this.reto.slice(startIndex, endIndex);
  }

  totalItems(): number {
    return this.reto.length;
  }

  onPageChange(event: any) {
    this.first = event.first;
    this.rows = event.rows;
  }

  /* changeRoute(ruta: string, params: object) {
    this.router.navigate([ruta], { queryParams: params });
  } */
}
